version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket magenta-server --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml